from . import hr_hospital_abstract_person
from . import hr_hospital_contact_person
from . import hr_hospital_doctor_speciality
from . import hr_hospital_doctor_schedule
from . import hr_hospital_diagnosis
from . import hr_hospital_patient_doctor_history
from . import hr_hospital_desease
from . import hr_hospital_doctor
from . import hr_hospital_patient
from . import hr_hospital_visit
